-- Tipos de datos - DataType

-- bigint numero
-- bit numero
-- char texto
-- date fecha
-- datetimeoffset fecha con zona horaria
-- decimal numero decimal con alta precision
-- float es un numero decimal pero no tiene buena precisión
-- geography
-- 
